# Site settings
title: KID-1912’s Blog
SEOTitle: KID-1912’s博客 | KID-1912’s Blog
header-img: img/atmosphere.jpg
email: heyutongxue@gmail.com
description: "写给自己的博客笔记"
keyword: "我的博客"
url: "http://KID-1912.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/KID-1912/KID-1912.github.io.git" # you code repository

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "coding改变生活，技术改变世界。"
sidebar-avatar: /img/user.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
weibo_username: 6591691052
zhihu_username: hei-yu-tong-xue
github_username: KID-1912
#facebook_username:  暂无
#jianshu_username:   暂无
#twitter_username:   暂无

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
timezone: Asia/Shanghai
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# pluginss
# from PR#40, to support local preview for Jekyll 3.0
pluginss: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
#redcarpet:
#    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
kramdown:
  input: GFM # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: false #是否开启Gitalk评论
  clientID: #生成的clientID
  clientSecret: #生成的clientSecret
  repo: name.github.io #仓库名称
  owner: #github用户名
  admin:
  distractionFreeMode: false #是否启用类似FB的阴影遮罩

# 统计

# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
ga_track_id: # Format: UA-xxxxxx-xx
ga_domain: # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true # 是否使用首页标签
featured-condition-size: 5 # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends:
  [
    { title: "github", href: "https://github.com/KID-1912" },
    { title: "掘金", href: "https://juejin.cn/user/3008684729329512" },
  ]
